### ISSUE TITLE
[Bug report] v.2.9.0 Don't show images

### ISSUE THREAD

**Issue by jcabak** [ptkdev-components/webcomponent-instagram-widget#14]
Script don't show images at all, description are fine.

https://codepen.io/ptkdev/pen/WNQOYqy

### Versions

- **WebComponent Version:** v2.9.0

### Screenshots (Optional)

![ 2021-08-04 at 18 19 59](https://user-images.githubusercontent.com/1818155/128217415-1ee7737d-59fe-4d4e-b4cc-fbe5642e5aba.png)

**Comment by ptkdev** [comment]
See #11
