### ISSUE TITLE
Instagram changed procedure to get his API

### ISSUE THREAD

**Issue by simooooone** [ptkdev-components/webcomponent-instagram-widget#5]
### Versions
**ALL**

- **WebComponent Version:** v1.0.0
- **Node Version:** v13.0.0
- **Operating System:** ALL
- **Browser:** ALL

### Expected Behavior

View the posts of an instagram profile

### Actual Behavior

Get this error in chrome dev tools:
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
And the webcomponent doesn't show up

### Steps to Reproduce

1. include the code provided in the README.md in a website
2. open the website
3. open web dev tools
4. got a JSON error 
5. **the instagram posts plugin doesn't show posts on the web page**

### Probably Solution

[https://www.instagram.com/developer/](https://www.instagram.com/developer/)
this page states that the old api doesn't work anymore and provide the steps for register to the access to the new API

**Comment by ptkdev** [comment]
1) [Work](https://codepen.io/ptkdev/pen/WNQOYqy) correctly on demo page.
2) Profile need be public (this webcomponent don't work with the private profiles)
3) If you refresh page or show this  webcomponent more than 50-60 times with same ip, you get the error of limits. Instagram's public APIs have limits. Try again after 24 hours.

**Comment by simooooone** [comment]
Hi patrik,
I don't have an instagram account.
Some times ago I put this component in a test website. I saw the web component and I used it.
Now I can't see it.
