### ISSUE TITLE
Can't change default username

### ISSUE THREAD

**Issue by yalesnikov** [ptkdev-components/webcomponent-instagram-widget#6]
Hello, I tried to set username into Angular version of the **webcomponent-instagram-widget** and also I tried to change default param at the demo-site, but it doesn't work: I saw photo from default profile.

**Comment by ptkdev** [comment]
Hi!
Thanks' for issue, i try fix demo-site as soon as possible.

**Comment by ptkdev** [comment]
Firebase demo app will be removed in v2.8.0, please use [codepen demo](https://codepen.io/ptkdev/pen/WNQOYqy). 

See [api rate limit](https://github.com/ptkdev-components/webcomponent-instagram-widget/issues/7#issuecomment-768435350) if you get previous images after change username.
