### ISSUE TITLE
Error while retrieving images

### ISSUE THREAD

**Issue by rafanb94** [ptkdev-components/webcomponent-instagram-widget#7]
Helloo,

I have the same problem that is appearing in your demo: https://webcomponents-60bc6.firebaseapp.com/instagram-widget

![image](https://user-images.githubusercontent.com/21113285/105938163-c9cb2900-6035-11eb-8f28-40d791d68148.png)

**Comment by ptkdev** [comment]
Hi!
- Firebase demo app don't work, don't use it #6, try [codepen demo](https://codepen.io/ptkdev/pen/WNQOYqy)
- You need a public instagram profile
- Don't use vpn or proxy
- Retry after 48h: your ip has reached request/daily limit for free instagram api**. Try with hotspot or other wifi network

** Instagram daily limit is 5-100 daily request from the same ip with free instagram api. This web component caches the last correct API response and retries to update it each time it receives a correct response to overcome the daily limit problem
