### ISSUE TITLE
error while retrieving images

### ISSUE THREAD

**Issue by nemanjadjurisic92** [ptkdev-components/webcomponent-instagram-widget#8]
### Versions

- **WebComponent Version:** v1.0.0
- **Node Version:** v13.0.0
- **Operating System:** Windows 10
- **Browser:** Google Chrome v80

### Expected Behavior
widget must show instagram pictures

### Actual Behavior
instead of instagram pictures I got this error "error while retrieving images...", I have latest update of webcomponent and also
profile is public. Please help!

### Steps to Reproduce

1. ...
2. ...
3. ...

**Comment by ptkdev** [comment]
Hi!
- You need a public instagram profile
- Don't use vpn or proxy
- Retry after 48h: your ip has reached request/daily limit for free instagram api**. Try with hotspot or other wifi network

** Instagram daily limit is 5-100 daily request from the same ip with free instagram api. This web component caches the last correct API response and retries to update it each time it receives a correct response to overcome the daily limit problem.

In many countries of the world the instagram api are extremely limited and some internet providers use the same ip range for many users which increases this problem. In the future in v3.0.0, opengraph api with secret token will be implemented for more experienced users and you get workaround for instagram api limits.
